Package to serve as a realsense reboot tester
plusone-robotics/realsense pull request #27
Opened 2019-05-20 17:53 UTC by abhijitmajumdar

A package is added to enable testing of the realsense cameras to make sure the they do not crash after rebooting the system from scratch and launching the cameras with `initial_reset` enabled

2020-09-10 20:11 UTC, 130s commented
Sorry or the very late response. The entire addition in this PR is a new package `realsense_test`, so I don't foresee adding this package will cause side effect on realsense2 package.

CI failed but CI config looks outdated and it's from the upstream, so I won't bother ourselves fixing it for now.

2020-09-10 20:25 UTC, 130s requested changes
@abhijitmajumdar I like the approach to make the "reboot test" self-contained within the driver package. Let's discuss if we can replace our reboot test with this (with possible need for some modifications that emerged over time).

Just added cosmetic change suggestions.

2020-09-10 20:25 UTC, 130s commented on realsense_test/Readme.md
> +git clone -b am_realsense_test https://github.com/abhijitmajumdar/realsense.git
```suggestion
git clone https://github.com/plusone-robotics/realsense.git
```

2020-09-10 20:25 UTC, 130s commented on realsense_test/package.xml
> +  <maintainer email="ros@todo.todo">ros</maintainer>
```suggestion
  <maintainer email="abhijit.majumdar@plusonerobotics.com">Abhijit Majumdar</maintainer>
```

2020-09-10 20:25 UTC, 130s commented on realsense_test/package.xml
> +  <license>TODO</license>
```suggestion
  <license>Apache License 2.0</license>
```

2023-04-24 16:56 UTC, aaronplusone commented
Closing since this is a couple years old and has no recent updates.

2023-04-24 16:56 UTC, closed without merging